### ISSUE TITLE
I found some crash issues

### ISSUE THREAD

**Issue by YYYSSSHHH** [ltguillaume/droidshows#91]
Environment Info：
DroidShow ：android:versionCode="71100" android:versionName="7.11.0"
AndroidOS  Version = 6.0.1

Description information：
	We find that mobile apps are prone to crashes due to a network issue, mainly because successful network API calls return unexpected or no data.
        And we found that when this app's network returned data is null ，or the network request fails (status code is 404/503) the app has crashed.

**crash information：**
	### crash one: 
crashActivity=nl.asymmetrics.droidshows.ui.ViewEpisode
:
java.lang.IllegalStateException: Could not execute method for android:onClick
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4458)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
	
... 9 more

Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.EDIT typ=vnd.android.cursor.item/event (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
	at android.app.Activity.startActivityForResult(Activity.java:3942)
	at android.app.Activity.startActivityForResult(Activity.java:3902)
	at android.app.Activity.startActivity(Activity.java:4231)
	at android.app.Activity.startActivity(Activity.java:4199)
	at nl.asymmetrics.droidshows.ui.ViewEpisode.calendarEvent(ViewEpisode.java:231)
	... 11 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.EDIT typ=vnd.android.cursor.item/event (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
	at android.app.Activity.startActivityForResult(Activity.java:3942)
	at android.app.Activity.startActivityForResult(Activity.java:3902)
	at android.app.Activity.startActivity(Activity.java:4231)
	at android.app.Activity.startActivity(Activity.java:4199)
	at nl.asymmetrics.droidshows.ui.ViewEpisode.calendarEvent(ViewEpisode.java:231)
	... 11 more
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.EDIT typ=vnd.android.cursor.item/event (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
	at android.app.Activity.startActivityForResult(Activity.java:3942)
	at android.app.Activity.startActivityForResult(Activity.java:3902)
	at android.app.Activity.startActivity(Activity.java:4231)
	at android.app.Activity.startActivity(Activity.java:4199)
	at nl.asymmetrics.droidshows.ui.ViewEpisode.calendarEvent(ViewEpisode.java:231)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:4453)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

### Crash Two:
crashActivity=nl.asymmetrics.droidshows.ui.SerieEpisodes
:
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{2533488 V.E...... R......D 0,0-647,271} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
	at android.app.Dialog.dismissDialog(Dialog.java:377)
	at android.app.Dialog.dismiss(Dialog.java:360)
	at nl.asymmetrics.droidshows.ui.AddSerie$1.run(AddSerie.java:128)
	at android.app.Activity.runOnUiThread(Activity.java:5552)
	at nl.asymmetrics.droidshows.ui.AddSerie$AsyncAddSerie.onPostExecute(AddSerie.java:298)
	at nl.asymmetrics.droidshows.ui.AddSerie$AsyncAddSerie.onPostExecute(AddSerie.java:189)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

Finally：
These crashes happened by accident when I was testing. I tried to reproduce them and found that they can't be reproduced, but they are real. I hope they can help you to debug.
The cause of the program crash may be that the network response data is not handled properly in the code,
If you have confirmed or fixed this problem, please give me a reply, thank you!

**Comment by ltguillaume** [comment]
Thanks for reporting, but I can't find in your report what button/text/item you actually clicked when the crashes occurred.

For the first one, I'm _guessing_ you clicked the episode's air date? In that case, (if you did this in an emulator) I suppose there was no Calendar app installed? The next version (see https://github.com/ltGuillaume/DroidShows/commit/3ee10712be39ae5fea71a3cdfbbcd0911d898231) will show an error message that no Calendar app was found (and not crash 😉).

For the second I'd really need more info.

**Comment by YYYSSSHHH** [comment]
I did run it on the simulator，and no Calendar app .  :smile:   
For the second crash ,I haven't found the reason.     If I find out, I'll tell you the first time.

**Comment by ltguillaume** [comment]
Cool! Thanks for that 🙂
